Presentación
En este apartado se fundamenta el trabajo realizado en nuestro proyecto, aplicando los conceptos de Programación Orientada a Objetos.
A partir del Diagrama de Clases, se logró un abordar el material trabajado en clase, plasmando el contenido en una estructura modular sólida.
Se implementaron pruebas unitarias (TDD) para cada método de las clases, lo que permitió garantizar el correcto funcionamiento del sistema.

Para ingresar de manera segura al PDF de la documentación del Diagrama de Clases de la Ev5, se comparte el link:
https://drive.google.com/file/d/1zuR_fk0-l7HMUruzFWtZBmCw_8pob3yU/view?usp=drive_link
