Presentación
En este apartado se fundamenta el trabajo realizado en nuestro proyecto, aplicando los conceptos de Programación Orientada a Objetos.
A partir del Diagrama de Clases, se logró un abordaje completo del material trabajado en clase, plasmando el contenido en una estructura modular sólida.
Se implementaron pruebas unitarias (TDD) para cada método de las clases, lo que permitió garantizar el correcto funcionamiento del sistema.
Además, siguiendo los principios SOLID, se consiguió escribir código flexible, mantenible y escalable, optimizando tanto el diseño de las clases como la interacción entre ellas.
